name: Test Python 🐍 before build

on:
  push:
    tags: -'test'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          make local_install
          make local_dev_install
      - name: Test with pytest
        run: |
          make mock-tests-unit
